# fly.toml app configuration file generated for glosa-gateway on 2026-07-13T01:32:25+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glosa-gateway'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
